---
- name: Install Development Packages
  hosts: localhost
  become: true
  tasks:
    - name: Install development packages
      apt:
        pkg:
          - ack
          - automake
          - build-essential
          - bzip2
          - curl
          - htop
          - jq
          - libxml2-utils
          - make
          - python3
          - python3-dev
          - python3-pip
          - tree
          - unzip
          - virtualenv
        state: present

- name: Install Development Tools
  hosts: localhost
  roles:
    - docker
    - git
    - golang
    - go-junit-report #Must run after golang
    - go-metalinter
    - go-testsum
    - terraform

