---
- name: Set TMUX to launch on shell entry
  hosts: localhost
  become: false
  roles:
    - set-user-facts
  tasks:
    - name: Set TMUX to launch on shell entry
      blockinfile:
        path: "{{ local_user_homedir }}/.bashrc"
        marker_begin: "BEGIN TMUX EXEC"
        marker_end: "END TMUX EXEC"
        block: |
          if command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]] && [ -z "$TMUX" ]; then
            exec tmux
          fi

- name: Configure WSL2
  hosts: localhost
  become: true
  tasks:
    - name: Configure wsl.conf
      template:
        src: "wsl.j2"
        dest: "/etc/wsl.conf"
        owner: root
        group: root
        mode: '0644'

    - name: Create a managed resolv.conf
      template:
        src: "resolv.j2"
        dest: "/etc/resolv.conf"
        owner: root
        group: root
        mode: '0644'
        follow: false

